### VARIABLES 
@baseURL = http://localhost:8080
@token = {{AuthenticateUser.response.body.access_token}}

###

# @name RegisterNewUser
POST {{baseURL}}/user/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@example.com",
    "password": "123456"
}

###

# @name AuthenticateUser

POST {{baseURL}}/user/auth
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "123456"
}

###

# @name GetProfile

GET {{baseURL}}/user/me
Authorization: Bearer {{token}}


###

# @name CreateNote

POST  {{baseURL}}/note/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "test",
    "column": "in-progress",
    "roomId": "32422c11-9640-4ee8-ba1e-0ed350a8df88"
}


###

# @name UpdateNote
PATCH {{baseURL}}/note/43646374-683d-4463-81d5-28c61e340383
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "test",
    "column": "done"
}

###

# @name DeleteNote

DELETE {{baseURL}}/note/43646374-683d-4463-81d5-28c61e340383
Authorization: Bearer {{token}}


###

# @name GetAllNote

GET  {{baseURL}}/note/get-all
Authorization: Bearer {{token}}


### 

# @name CreateRoom
POST {{baseURL}}/room/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "roomName": "sala de serviço"
}


###

# @name GetRoomInfo
GET {{baseURL}}/room/info/e58f632a-4312-4826-8499-1156f5432c73
Authorization: Bearer {{token}}

###

# @name DeleteRoom
DELETE {{baseURL}}/room/e58f632a-4312-4826-8499-1156f5432c73
Authorization: Bearer {{token}}